# Generated by Django 3.0.14 on 2023-03-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Granja', '0002_alimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propietario', models.CharField(max_length=30)),
                ('celular_propietario', models.CharField(max_length=80)),
                ('ubicacion_propietario', models.CharField(max_length=30)),
            ],
        ),
    ]
